name: 'energy_risk'
version: '1.0.0'

profile: 'energy_risk'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  energy_risk:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  energy_risk: {}
